[paths]
labeled_dir = "/home/chenyu/workspace/data/labeled_data"           # 数据集路径
unlabeled_dir = "/home/chenyu/workspace/data/unlabeled_data"   # 数据集划分路径
output_dir = "./outputs+test"                    # 实验输出路径

[training]
gpu_id = 1
epochs = 450
warmup_epoch = 10
batch_labeled = 10
batch_unlabeled = 10
learning_rate = 0.001
alpha = 0.999           # 动态alpha todo


