# arguments for dataset
dataset: acdc
nclass: 3
crop_size: 512
data_root: oursdataPath
# arguments for training
epochs: 400
batch_size: 1 # per GPU x 1 GPU
# lr: 0.01
lr: 0.000005
conf_thresh: 0.95
model: dpt
# backbone: dinov2_small
backbone: dinov3_small
lr_multi: 40.0
lock_backbone: False
